apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: final-project
data:
  nginx.conf: |
    events {}
    http {
      upstream backendpool {
        least_conn;
        server backend-service:5000;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://backendpool;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer
  namespace: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-loadbalancer
  template:
    metadata:
      labels:
        app: nginx-loadbalancer
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: final-project
spec:
  type: NodePort
  selector:
    app: nginx-loadbalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
